VIEWPORT_WIDTH = 1280
VIEWPORT_HEIGHT = 720
VIEWPORT_CENTER_X = VIEWPORT_WIDTH / 2
VIEWPORT_CENTER_Y = VIEWPORT_HEIGHT / 2

FONT_TITLE = 48
FONT_SUBTITLE = 36
FONT_NORMAL = 24

FONTS = "assets/fonts/"
VCR_OSD_MONO = FONTS + "VCR_OSD_MONO_1.001.ttf"
SPRITES = "assets/sprites/"
SPRITES_COMMON = SPRITES + "scenes/common"
SPRITES_EDITION = SPRITES + "scenes/intro"
SPRITES_EDITION = SPRITES + "scenes/edition"
SPRITES_OPTIMIZATION = SPRITES + "scenes/optimization"