import pygame

VIEWPORT_WIDTH = 1280	
VIEWPORT_HEIGHT = 720
VIEWPORT_CENTER_X = VIEWPORT_WIDTH / 2
VIEWPORT_CENTER_Y = VIEWPORT_HEIGHT / 2
VIEWPORT_PADDING_X = 16
VIEWPORT_PADDING_Y = 32

POPUP_X = 79
POPUP_Y = 79
POPUP_WIDTH = 1122
POPUP_HEIGHT = 544

FONT_TITLE = 48 - 4 # 48
FONT_SUBTITLE = 36 - 4 # 36
FONT_NORMAL = 24 - 4 # 24
FONT_SMALL = 18 - 4 # 18

FONTS = 'assets/fonts/'
VCR_OSD_MONO = FONTS + 'VCR_OSD_MONO_1.001.ttf'
SPRITES = 'assets/sprites/'
SPRITES_COMMON = SPRITES + 'scenes/common/'
SPRITES_EDITION = SPRITES + 'scenes/intro/'
SPRITES_EDITION = SPRITES + 'scenes/edition/'
SPRITES_OPTIMIZATION = SPRITES + 'scenes/optimization/'
SPRITES_UI_BG = SPRITES_COMMON + 'ui-background.png'
MATERIAL = 'assets/material/'
EVENTS = 'assets/events/'

PALETTE_WHITE = (234, 225, 243)
PALETTE_PINK = (241, 100, 243)
PALETTE_CYAN = (163, 223, 224)
PALETTE_BLUE = (9, 9, 67)
PALETTE_DARK_BLUE = (17, 5, 45)
PALETTE_YELLOW = (237, 225, 74)
PALETTE_GREEN = (77, 232, 140)

PALLETE_DARK_BLUE = (0x1D, 0x72, 0xA7)
PALLETE_BACKGROUND_BLUE = (0x20, 0xF4, 0xFE)

MINIGAME_LEFT = 0
MINIGAME_RIGHT = 1

EMPTY_LCD_LABEL = ''

STORY_HOOK = 0
STORY_CONFLICT_1 = 1
STORY_CONFLICT_2 = 2
STORY_CONCLUSION = 3
STORY_SUBJECT_1 = 'S1'
STORY_SUBJECT_2 = 'S2'

# in minutes
SESSION_TIME = 10.1

# TODO: put the constants related to the keyboard keys that will emulate the buttons
#   in la MiMo.